var data = {
    items:{
        Snack:{
            Life:10
        },
        Meal:{
            Life:20
        },
        Tonic:{
            Magic:15
        }
    },
    spells:{
        Fireball:{
            Magic:-10,
            Hit:20
        },
        Shield:{
            Magic:-15,
            Block:30
        },
        Heal:{
            Magic:-10,
            Life:20
        }
    },
    Weapon:{
        Daggar:10,
        Club:15,
        ShortSword:25,
        BroadSword:40,
    },
    Armor:{
        Leather:15,
        Iron:25,
        Bronze:30,
    },
    Shield:{
        Wooden:5,
        Iron:20,
        Bronze:25
    },
    Enemies:{
        Blob:{
            Life:10,
            Hit:10
        },
        Phantom:{
            Life:40,
            Hit:5
        },
        Goblin:{
            Life:25,
            Hit:5,
            Block:5,
            Weapon:"Daggar"
        },
        Witch:{
            Life:25,
            Hit:10,
            Magic:40
        },
        Ogre:{
            Life:50,
            Hit:20,
            Block:10,
            Armor:"Iron",
            Weapon:"Club"
        },
        Sorcerer:{
            Life:80,
            Hit:5,
            Block:5,
            Magic:80
        }
    },
    levels:[{
        Boss:"Witch",
        length:15,
        ratios:{
            Snack:20,
            Meal:15,
            Tonic:10,
            Daggar:10,
            Club:30,
            Leather:20,
            Wooden:10,
            Blob:30,
            Phantom:15,
            Goblin:15
        }
    },{
        Boss:"Ogre",
        length:25,
        ratios:{
            Snack:15,
            Meal:10,
            Tonic:15,
            Daggar:30,
            Club:40,
            ShortSword:10,
            Leather:25,
            Iron:10,
            Wooden:20,
            Iron:5,
            Blob:30,
            Phantom:20,
            Goblin:15,
            Witch:5
        }
    },{
        Boss:"Sorcerer",
        length:35,
        ratios:{
            Snack:10,
            Meal:5,
            Tonic:20,
            Daggar:10,
            Club:25,
            ShortSword:25,
            BroadSword:10,
            Leather:15,
            Iron:25,
            Bronze:10,
            Wooden:10,
            Iron:30,
            Bronze:15,
            Blob:20,
            Phantom:20,
            Goblin:20,
            Witch:15,
            Ogre:10
        }
    }],
    playerDefaults:{
        Life:100,
        Hit:10,
        Block:5,
        Magic:20
    },
    gameMenues:{
        move:["Left","Forward","Right"],
        battle:{
            Attack:{
                fightOrFlight:true,
                offenseOrDefense:true,
            },
            Guard:{
                fightOrFlight:true,
                offenseOrDefense:false,
            },
            Run:{
                fightOrFlight:false,
                menu:"turn",
            },
            "Cast Spell":{
                menu:"spells",
                useOrView:true,
            },
            "Read Spell":{
                menu:"spells",
                useOrView:false,
            },
            "Use Item":{
                menu:"items",
                useOrView:true,
            },
            "View Item":{
                menu:"items",
                useOrView:false,
            },
            "View Player":{
                showAll:true
            }
        },
        turn:{
            Go:{
                menu:"move",
            },
            "Cast Spell":{
                menu:"spells",
                turnOrBattle:true,
                useOrView:true
            },
            "Read Spell":{
                menu:"spells",
                useOrView:false
            },
            "Use Item":{
                menu:"items",
                useOrView:true
            },
            "View Item":{
                menu:"items",
                useOrView:false
            },
            "View Player":{
                showAll:true
            }
        }
    }
};
